// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIzHXRdlXZt6YPDSDLOdzrsjJcvgtjJE0',
    appId: '1:319153694445:web:af1bd31b96d224c99a4ee4',
    messagingSenderId: '319153694445',
    projectId: 'aunar-points',
    authDomain: 'aunar-points.firebaseapp.com',
    storageBucket: 'aunar-points.appspot.com',
    measurementId: 'G-ZY7Z1FGYHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM0742sHykwJae58QCtJoGtsGA2FIYLyk',
    appId: '1:319153694445:android:edb27ef8b36310369a4ee4',
    messagingSenderId: '319153694445',
    projectId: 'aunar-points',
    storageBucket: 'aunar-points.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmg8un5usLP-KJoaMIV1Rae4uI8hQ13fw',
    appId: '1:319153694445:ios:dd33ba1384173fe59a4ee4',
    messagingSenderId: '319153694445',
    projectId: 'aunar-points',
    storageBucket: 'aunar-points.appspot.com',
    iosBundleId: 'com.example.aunarPoints',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmg8un5usLP-KJoaMIV1Rae4uI8hQ13fw',
    appId: '1:319153694445:ios:dd33ba1384173fe59a4ee4',
    messagingSenderId: '319153694445',
    projectId: 'aunar-points',
    storageBucket: 'aunar-points.appspot.com',
    iosBundleId: 'com.example.aunarPoints',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIzHXRdlXZt6YPDSDLOdzrsjJcvgtjJE0',
    appId: '1:319153694445:web:e36563a3372deb109a4ee4',
    messagingSenderId: '319153694445',
    projectId: 'aunar-points',
    authDomain: 'aunar-points.firebaseapp.com',
    storageBucket: 'aunar-points.appspot.com',
    measurementId: 'G-E625WGQJCN',
  );
}
